### PR TITLE
Config file support

### PR DESCRIPTION
**Pull request by AndresCidoncha**
I simply add the option of using a YAML file for configuring the service. Configurations loaded from file have the highest priority over others methods (cli params, env variables).

My idea is made multiples PR for achieving the multiple bucket configuration feature.

### CODE REVIEW

**Comment by fivehorizons** [comment]
Baller pull request.  Let me look at what you have done.

**Comment by fivehorizons** [comment]
@andrescidooncha did you include the TF0.12 enablement?

**Comment by AndresCidoncha** [comment]
I'd check out this branch from master. 

Do you mean these changes? https://github.com/camptocamp/terraboard/pull/62

**Comment by raphink** [comment]
@AndresCidoncha thanks for these changes. There's quite a few (good) things in here, and I would rather not squash everything together. Do you think you could squash these into a couple of well-defined feature commits?

**Comment by AndresCidoncha** [comment]
Sure! I'll do ASAP

**Comment by raphink** [comment]
@AndresCidoncha Note I just merged #62 (finally!) so you'll need to rebase (incl switching to go modules)

**Comment by AndresCidoncha** [comment]
@raphink I merged your changes and I also fixed the problem with `golint` in `make test`!

**Comment by raphink** [comment]
@AndresCidoncha thanks. There seems to be conflicts still, can you check?

**Comment by AndresCidoncha** [comment]
@raphink I can't see the conflicts :confused: The change list seems to be ok, and GitHub say: `This branch has no conflicts with the base branch`

**Comment by raphink** [comment]
Weird…

Screenshot from 2019-10-29 15-21-01

**Comment by AndresCidoncha** [comment]
Yep, really weird:
image
Can you see the conflicting files in your end so I can try to fix it?

**Comment by falcon47** [comment]
Maybe is due to trying to rebase instead of merge? As we don't have permission to merge, maybe github is showing the checks to merge, not rebase.

**Comment by raphink** [comment]
Ah right, merging is possible, just not rebasing.

**Comment by AndresCidoncha** [comment]
@raphink You tell me rebase and I merge your changes. My bad. I'll have to fix it :cry:

**Pull request merged**
