### PR TITLE
option to switch go dns resolver

### PR DESCRIPTION
**Pull request by mihaiplesa**
For https://github.com/camptocamp/terraboard/issues/118

### CODE REVIEW

**Comment by raphink** [comment]
What are the potential side effects of using the pure go DNS resolver?

**Comment by mihaiplesa** [comment]
This is just an option. It would fix DNS resolution in Docker and the cloud though for the ones having issues.

**Comment by raphink** [comment]
Thanks for the reply. Could you rebase so Travis might pass please?

**Comment by mihaiplesa** [comment]
On it now.

**Pull request merged**
