### PR TITLE
Bumped all dependencies / TF 0.14.5 / TFE 0.12.0

### PR DESCRIPTION
**Pull request by mvisonneau**
```shell
~$ go get -u ./...
~$ go mod tidy
```

### CODE REVIEW

**Comment by raphink** [comment]
Does this need a rebase with #132 merged?

**Comment by mvisonneau** [comment]
I feel that it should be fine 🤔

**Comment by raphink** [comment]
Ah, the build passes now, I just needed to restart it it seems. However, there is now a conflict on `go.mod`

**Comment by mvisonneau** [comment]
Ah right, I just rebased it should be fine now 👍

**Comment by raphink** [comment]
It's still failing to build

**Comment by mvisonneau** [comment]
Indeed my bad, most likely related to https://github.com/camptocamp/terraboard/pull/133 🙇

**Comment by raphink** [comment]
I've merged #133 . Can you rebase please @mvisonneau ?

**Comment by mvisonneau** [comment]
done, @raphink! 😃

**Comment by mvisonneau** [comment]
omg I messed up 😓 , one sec1

**Comment by mvisonneau** [comment]
ok good to go know 👌

**Comment by raphink** [comment]
Let's wait for Travis 👷⌚

**Pull request merged**
