### PR TITLE
Support Terraform 0.12

### PR DESCRIPTION
**Pull request by raphink**
This PR aims to support Terraform 0.12. This implies to support multiple version state formats, which requires to use the `statefile` API.

### CODE REVIEW

**Comment by fivehorizons** [comment]
I was trying to build the image and keep getting same error on different machines 

`go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
        fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection refused
go: error loading module requirements
make: *** [Makefile:7: terraboard] Error 1
ERROR: compose.cli.main.main: Service 'terraboard' failed to build: The command '/bin/sh -c make terraboard' returned a non-zero code: 2`

**Comment by fivehorizons** [comment]
added replace to go.mod to fix Apache git issues https://status.apache.org/


replace git.apache.org/thrift.git => github.com/apache/thrift v0.0.0-20180902110319-2566ecd5d999

**Comment by fivehorizons** [comment]
This branch is fully working up to 12.7 terraform. Even the chart on right works.  If we can finalize this pull

**Comment by AndresCidoncha** [comment]
@raphink I think that you need to update the `.travis.yml` file for using `go mod`.

**Comment by raphink** [comment]
@AndresCidoncha good point, changing that now

**Pull request merged**
