### PR TITLE
feat: allow more than 1000 state files

### PR DESCRIPTION
**Pull request by lorodoes**
Upgrade to the newest AWS API For ListObjectsV2 and then also add the ability to have more than 1000 state files

### CODE REVIEW

**Review by raphink — APPROVED** [review]
LGTM

**Comment by raphink** [comment]
The AWS tests are actually failing. @hbollon do you see why?

**Comment by hbollon** [comment]
Hi guys!
In order to be able to mock AWS provider for testing purposes, I created a custom type `s3Mock` implementing the `s3iface.S3API` interface and defined needed methods for our use cases (`ListObjects`, `ListObjectVersions`, etc.).

**from `aws_test.go`:**
```go
type s3Mock struct {
	s3iface.S3API
}

func (s *s3Mock) ListObjects(_ *s3.ListObjectsInput) (*s3.ListObjectsOutput, error) {
	return &s3.ListObjectsOutput{Contents: []*s3.Object{{Key: aws.String("test.tfstate")}}}, nil
}
func (s *s3Mock) ListObjectVersions(_ *s3.ListObjectVersionsInput) (*s3.ListObjectVersionsOutput, error) {
	return &s3.ListObjectVersionsOutput{
		Versions: []*s3.ObjectVersion{
			{Key: aws.String("testId"), VersionId: aws.String("test"), LastModified: aws.Time(time.Now())},
			{Key: aws.String("testId2"), VersionId: aws.String("test2"), LastModified: aws.Time(time.Now())},
		},
	}, nil
}
func (s *s3Mock) GetObjectWithContext(_ aws.Context, _ *s3.GetObjectInput, _ ...request.Option) (*s3.GetObjectOutput, error) {
	return &s3.GetObjectOutput{
		Body: ioutil.NopCloser(bytes.NewReader([]byte(`{"Version": 4, "Serial": 3, "TerraformVersion": "0.12.0"}`))),
	}, nil
}
```

So with the AWS API upgrade and the use of `ListObjectsV2` instead of `ListObjects` the program panic since this function is not defined on `a.svc` which is of type `s3Mock` during unit tests (cf. [line 150 of aws.go](https://github.com/camptocamp/terraboard/blob/b8352f5c5f6c7682df36ff06d9453c48b5c8930b/state/aws.go#L150)).
To solve this we must add mocked `ListObjectsV2` method on `s3Mock`  :+1:

**Comment by lorodoes** [comment]
@hbollon Sorry I didn't update the aws_test.go, I see how to do it, but it might be a bit before I can complete it.

**Comment by bmpandrade** [comment]
Is they any updates on this PR? Or is it possible for me to help on moving it further?

\cc @raphink @lorodoes

**Comment by lorodoes** [comment]
@bmpandrade I updated the PR with an updated version of aws_test.go. I think the workflow just needs to be rerun again to verify that everything is working as expected.

**Comment by bmpandrade** [comment]
@lorodoes , I took a look at the worfklows, but none allow for re-run, it requires explicit approval from maintainers to run them again.

**Comment by bmpandrade** [comment]
@raphink @hbollon Do you mind giving a peak here, please? 🙏

**Comment by hbollon** [comment]
Hi guys, 
Tests were always failing, I fixed the mocked function for `ListObjectsV2` and it's all good now.
@raphink it's all good to you? Can we merge?

**Review by hbollon — APPROVED** [review]

**Review by raphink — APPROVED** [review]

**Comment by raphink** [comment]
OK for me @hbollon

**Pull request merged**
