### PR TITLE
New flat logo

### PR DESCRIPTION
**Pull request by raphink**
Following #32, here is a new suggestion of a logo for Terraboard. It is:

- based on the letters "t" and "b" (see the [Comfortaa](https://www.fontsquirrel.com/fonts/comfortaa) font for the model)
- a planet in the process of being terraformed
- an arrow to evoke the transformation process

terraboard_logo_only

terraboard_logo

### CODE REVIEW

**Comment by raphink** [comment]
For the record, here are the attempts on the way (still included in the SVG)

g5471

**Comment by mcanevet** [comment]
@raphink shouldn't we use Camptocamp's orange?

**Comment by raphink** [comment]
@mcanevet that's the orange I used in the original design, see the orange logos at the bottom right in my previous post. I don't think it looks very good tbh

**Comment by raphink** [comment]
A new version thanks to @ckaenzig's suggestions

terraboard_logo_only

terraboard_logo

**Comment by raphink** [comment]
With a thicker border

terraboard_logo_only
terraboard_logo

**Pull request merged**
