### PR TITLE
Switch submodule hugo-elate-theme to https

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by gliptak** [comment]
@raphink This gets Travis along and now fails in tests

https://travis-ci.org/camptocamp/terraboard/builds/463095134

**Comment by raphink** [comment]
Good point, thanks.

**Comment by gliptak** [comment]
@raphink did you have a chance to look into the tests failing?

**Comment by raphink** [comment]
They're definitely not linked to this PR, so I'll merge this and I'll look later.

**Pull request merged**
