### PR TITLE
Add support for outputs (Fix #50)

### LINKED ISSUE #50: View for outputs
It would be very good if terraform outputs also has they own view. I see that the contributor is no longer develop this beautiful tool but maybe some one else can do this. 
Thanks a lot.

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by raphink** [comment]
Not very satisfied with the interface and storing the values as strings in the DB…

Here's a screenshot of the current status:

screenshot from 2018-10-31 16-37-19

**Comment by tedder** [comment]
This is good. Are you planning on making your own releases, @raphink ?

**Comment by raphink** [comment]
@tedder I'm the main author of Terraboard so I make the official releases, I just don't have much time to work on it lately… I'll try to rebase this once I have #62 and #64 merged.

**Comment by raphink** [comment]
This PR needs to be reviewed after #62 was merged, since the switch to github.com/hashicorp/terraform/states/statefile means we have no access to Outputs directly anymore.

**Pull request closed without merging**
