### PR TITLE
Added Minio as a private alternative to AWS S3

### PR DESCRIPTION
**Pull request by tibeer**
We required Minio as a state backend. As it does not store file versions by default and has also a slightly different handling than AWS S3, I decided to write my own "state provider". File versioning and locking might be added in the future, but is not yet implemented.

Signed-off-by: Tim Beermann <beermann@betacloud-solutions.de>

### CODE REVIEW

**Comment by mcanevet** [comment]
I guess we should treat all s3-compatible implementation the same way and not doing anything specific to minio.
Maybe it's just about adding some additional parameters to the current structure.

**Comment by berendt** [comment]
> I guess we should treat all s3-compatible implementation the same way and not doing anything specific to minio.
> Maybe it's just about adding some additional parameters to the current structure.

@mcanevet At the moment there is no standalone S3 state plugin. The current AWS plugin depends on S3 as well as DymoDB. We use Minio for our states and would like to visualize this via Terraboard. We are not interested in a generic S3 provider.

**Comment by hbollon** [comment]
I have opened #165  which should normally meet your needs.
She should be merge soon :+1:

**Comment by raphink** [comment]
#165 was merged, so Minio should be usable now.

**Comment by berendt** [comment]
Cool. Thanks. We are testing it in a timely manner.

**Comment by tibeer** [comment]
Works for us! Thanks a lot!

**Pull request closed without merging**
